---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, cloud manager, bluexp' 
summary: Scopri le novità di Kubernetes in BlueXP. 
---
= Novità di Kubernetes in BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le novità di Kubernetes in BlueXP (Cloud Manager).



== 02 aprile 2023

* Ora puoi farlo link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-trident.html["Disinstallare Astra Trident"] Che è stato installato utilizzando l'operatore Trident o BlueXP.
* Sono stati apportati miglioramenti all'interfaccia utente e sono state aggiornate le schermate nella documentazione.




== 05 marzo 2023

* Kubernetes in BlueXP supporta ora Astra Trident 23.01.
* Sono stati apportati miglioramenti all'interfaccia utente e sono state aggiornate le schermate nella documentazione.




== 06 novembre 2022

Quando link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-storage-classes.html#add-storage-classes["definizione delle classi di storage"], è ora possibile abilitare lo storage economy di classe storage per lo storage a blocchi o su file system.



== 18 settembre 2022

Ora puoi importare cluster OpenShift autogestiti in Cloud Manager.

* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/requirements/kubernetes-reqs-openshift.html["Requisiti per i cluster Kubernetes in OpenShift"]
* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-kubernetes-discover-openshift.html["Importare un cluster OpenShift in Cloud Manager"]




== 31 luglio 2022

* Utilizzando il nuovo `- watch` Nella classe di storage e nelle configurazioni YAML di backup e ripristino, Cloud Manager può ora monitorare i cluster Kubernetes per le modifiche apportate al backend del cluster e abilitare automaticamente il backup per nuovi volumi persistenti se è stato configurato il backup automatico sul cluster.
+
link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/requirements/kubernetes-reqs-aws.html["Requisiti per i cluster Kubernetes in AWS"]

+
link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/requirements/kubernetes-reqs-aks.html["Requisiti per i cluster Kubernetes in Azure"]

+
link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/requirements/kubernetes-reqs-gke.html["Requisiti per i cluster Kubernetes in Google Cloud"]

* Quando link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-storage-classes.html#add-storage-classes["definizione delle classi di storage"], è ora possibile specificare un tipo di file system (fstype) per lo storage a blocchi.




== 3 luglio 2022

* Se Astra Trident è stato implementato utilizzando l'operatore Trident, è ora possibile eseguire l'aggiornamento alla versione più recente di Astra Trident utilizzando Cloud Manager.
+
link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-trident.html["Installare e gestire Astra Trident"]

* È ora possibile trascinare il cluster Kubernetes e rilasciarlo nell'ambiente di lavoro AWS FSX per ONTAP per aggiungere una classe di storage direttamente da Canvas.
+
link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-storage-classes.html#add-storage-classes["Aggiungere classe di storage"]





== 6 giugno 2022

Cloud Manager ora supporta Amazon FSX per ONTAP come storage back-end.



== 4 maggio 2022



=== Trascinare e rilasciare per aggiungere la classe di storage

È ora possibile trascinare il cluster Kubernetes e rilasciarlo nell'ambiente di lavoro Cloud Volumes ONTAP per aggiungere una classe di storage direttamente da Canvas.

link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-storage-classes.html#add-storage-classes["Aggiungere classe di storage"]



== 4 aprile 2022



=== Gestire i cluster Kubernetes utilizzando la pagina delle risorse di Cloud Manager

Kubernetes Cluster Management ha ora migliorato l'integrazione direttamente dall'ambiente di lavoro del cluster. Un nuovo link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-quick-start.html["Avvio rapido"] ti consente di iniziare a lavorare rapidamente.

È ora possibile eseguire le seguenti operazioni dalla pagina delle risorse del cluster.

* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-trident.html["Installare Astra Trident"]
* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-storage-classes.html["Aggiungere classi di storage"]
* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-persistent-volumes.html["Visualizzare volumi persistenti"]
* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-k8s-manage-remove-cluster.html["Rimuovere i cluster"]
* link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/task/task-kubernetes-enable-services.html["Abilitare i servizi dati"]




== 27 febbraio 2022



=== Supporto per i cluster Kubernetes in Google Cloud

Ora puoi aggiungere e gestire cluster gestiti di Google Kubernetes Engine (GKE) e cluster di Kubernetes autogestiti in Google Cloud utilizzando Cloud Manager.

link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/requirements/kubernetes-reqs-gke.html["Scopri come iniziare a utilizzare i cluster Kubernetes in Google Cloud"].



== 11 gennaio 2022



=== Supporto per i cluster Kubernetes in Azure

Ora puoi aggiungere e gestire cluster di Azure Kubernetes gestiti (AKS) e cluster di Kubernetes autogestiti in Azure utilizzando Cloud Manager.

link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/requirements/kubernetes-reqs-aks.html["Introduzione ai cluster Kubernetes in Azure"]



== 28 novembre 2021



=== Supporto per i cluster Kubernetes in AWS

Ora puoi aggiungere i cluster Kubernetes gestiti a Canvas di Cloud Manager per una gestione avanzata dei dati.

* Scopri i cluster Amazon EKS
* Eseguire il backup dei volumi persistenti utilizzando Cloud Backup


link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/concept-kubernetes.html["Scopri di più sul supporto di Kubernetes"].


TIP: Il servizio Kubernetes esistente (disponibile tramite la scheda *K8s*) è stato obsoleto e verrà rimosso in una release futura.
